# Generated by Django 3.0.5 on 2020-05-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200428_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Transfer', 'Transfer')], max_length=15),
        ),
    ]
