# Generated by Django 3.0.5 on 2020-05-05 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200503_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Budget'),
        ),
        migrations.AlterField(
            model_name='budgettransaction',
            name='trans_type',
            field=models.CharField(default='Expense', max_length=15),
        ),
    ]
