# Generated by Django 3.0.5 on 2020-05-06 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200505_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='balance_currency',
        ),
    ]
