# Generated by Django 3.0.5 on 2020-05-06 22:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200506_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), default_currency='USD', max_digits=14),
        ),
        migrations.AddField(
            model_name='budget',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='budget',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Budget'),
        ),
    ]
